### ISSUE TITLE
disallow putting empty key into the map

### ISSUE THREAD

**Issue by phritz** [rocicorp/repc#124]
the key has to be non-empty, else we can't distinguish removing it from a top-level remove in patch. a top level remove is `{"op": "remove", "path": "/"}`, and so would be removing the empty key.

**Comment by arv** [comment]
It is not clear to me if we need to disable the key `""`. I looked at the specs for JSON Patch and JSON Path and it seems like the path `""` is the whole document and the path `"/"` is the value of the key `""`. I will see what happens in our code.

**Comment by arv** [comment]
I did some more research. `""` is clearly the root. Normally it makes no sense to remove the root, replacing the root works in some of the online demos I found though.

Are we relying on `"/"` to mean clear the db? I see this https://github.com/rocicorp/repc/blob/master/src/sync/patch.rs#L36 but are we generating this? Can we use `{"op": "replace", "path": "", "value": {}}` instead?

**Comment by phritz** [comment]
The diff of the noms maps doesn't ever generate a top-level remove of "/" but diffserver [returns it](https://github.com/rocicorp/diff-server/blob/b7795834dabecc13e6c54ce761efa9f9612202c6/db/diff.go#L15) in [several cases](https://github.com/rocicorp/diff-server/blob/b7795834dabecc13e6c54ce761efa9f9612202c6/db/diff.go#L48), eg if it doesn't have a copy of their base state. 

To answer your question yes we are relying on remove "/" to clear the db. This is different than what json path would suggest, which as you say is remove "". Our diff and patch came from noms so my guess is there was some reason lost to time that we [required patch keys to start with "/"](https://github.com/rocicorp/diff-server/blob/bf27412b085fb8fba1b3d4393e0f7d199fbb2cbd/util/noms/jsonpatch/jsonpatch.go#L121) and it just got carried over into the diffserver. 

Seems like the right resolution here is to fix this patch syntax we use instead of disallowing empty key.

**Comment by arv** [comment]
I see that we have a `version` param. Maybe this is the right time to use version `2`?

https://github.com/rocicorp/repc/blob/740b0482c69ee3160d0dce3a9cb5770db06eb084/src/sync/mod.rs#L119

**Comment by phritz** [comment]
Yes. Though we haven't really settled on a general strategy, this is more of a special case. https://github.com/rocicorp/repc/issues/119 covers a few related things and I'm supposed to make a proposal at some point.

**Comment by arv** [comment]
Here is the dance:

1. Update diff-server to support the new version (this is called `2` which is the third version) as well as the two old versions (`0` or missing and `1`). https://github.com/rocicorp/diff-server/pull/62
2. Change `repc` to send `version: 2` and expect version `2` response. https://github.com/rocicorp/repc/pull/213

This means that if someone is running their own diff-server they will need to get a newer one once we do a new release of repc.

I wonder if we want to:
 - send back the version?
 - assert a known version?
but this can be discussed in #119

**Comment by phritz** [comment]
Both changes LGTM, thanks.

> > I wonder if we want to:
> 
> send back the version?

good question. we haven't needed to yet and i kind of hope we can get away with not doing so for simplicity's sake.

> assert a known version?

yes. for now while we have a small number of customers we should have an aggressive sunsetting policy for old versions to keep the complexity of the diffserver down. eventually we'll have to support old versions for longer periods of time.
