### ISSUE TITLE
WriteTransactions and rollback difficult to use correctly

### ISSUE THREAD

**Issue by aboodman** [rocicorp/repc#136]
Currently, the wasm tests pass but report several cryptic exceptions about closures being called re-entrantly to the console.

These exceptions are also present in our sample apps, except in that case they crash the app because the exception bubbles all the way up to window.onerror.

I've tracked this down. The immediate issue is that the event handlers [registered by `WriteTransaction`](https://github.com/rocicorp/repc/blob/master/src/kv/idbstore.rs#L229) are firing after `WriteTransaction` has already been destroyed.

The reason *that* is happening is because [the `closeTransaction` RPC](https://github.com/rocicorp/repc/blob/master/src/embed/connection.rs#L322) just deletes `WriteTransaction` without calling `dag::Write::rollback()`. Thus the underlying idb transaction is still open when `IDBStore::Write` is destroyed. Later on, when the idb tx auto-commits, the complete event gets called but the corresponding Rust closure is gone.

Initially, I thought the "better" way to fix this was to ensure that rollback always gets called: https://github.com/rocicorp/repc/pull/135

However, this is very difficult because there are so many places we create `db::WriteTransaction`. Every single one of them needs to ensure `rollback()` is called or we will see this issue. This is especially difficult in cases like sync where we have [lots of early exits while a tx is open](https://github.com/rocicorp/repc/blob/master/src/sync/mod.rs#L94).

===

Stepping back, I'm not really sure what the explicit rollback is buying us. Why don't we just remove `rollback` and have only `commit` and drop (which implicitly rolls back)? That is clearly how existing callers expect it to work :).

IDBStore auto-commits (instead of auto-rollback), which doesn't match our desired semantics, but:

(a) We have our code around our usage of idb setup to not write anything into the transaction until an explicit call to `idb::Write::commit()` from our user. So there is no danger of us actually auto-committing an incomplete write. I'm not sure if we can even observe the fact that we'd implicitly commit an empty tx, rather than abort it.
(b) We could, theoretically, actually issue an abort to idb inside the destructor. The [underlying idb abort() method is synchronous](https://github.com/rocicorp/repc/blob/master/src/kv/idbstore.rs#L347), and the only reason our rollback method is async is because of the [lock](https://github.com/rocicorp/repc/blob/master/src/kv/idbstore.rs#L342) we used to track state. We could replace that with an atomic.

**Comment by phritz** [comment]
> The reason that is happening is because the closeTransaction RPC just deletes WriteTransaction without calling dag::Write::rollback()

Ugh. I pointed this out during code review, but obviously didn't understand how significant it was else I would've followed up: https://github.com/rocicorp/repc/pull/71/files/1fcd39fc0fd38d33201b6a3e9a4d92aae3bc4082#r467233587

> Why don't we just remove rollback and have only commit and drop (which implicitly rolls back)? That is clearly how existing callers expect it to work :).

That sounds like the right goal because it matches what I would expect, and, uh, did expect. Though it was more like I wasn't thinking about closing the txs at all. 

(b) sounds cleaner but I guess we would want to keep an eye out if it makes dropping txs expensive time wise. Is another option to introduce an long-lived intermediary on which the callbacks fire that can turn callbacks on dropped txs into nops? Or is that just asking for lifetime troubles?

**Comment by phritz** [comment]
re b i also think i would want to know more how abort works because having the whole system just stop for a while is obviously not super appealing

**Comment by aboodman** [comment]
I think I would start by just trying (a) and see if it's problematic in any way. I can't think of a way it would be, and (b) should be possible if necessary at some point.

**Comment by arv** [comment]
This is no longer relevant.

I removed rollback since the way we structure IDBStore we do not write anything until commit is called so there is really nothing to rollback.
