### ISSUE TITLE
Implement logging of request/response pairs

### ISSUE THREAD

**Issue by aboodman** [rocicorp/repc#148]

**Comment by phritz** [comment]
I'd like to do the minimum to get this out the door and I will file a separate issue for logging more generally in repc. As to what the minimum is: what is it? If we primarily care about wasm repc and we have browser tools for live debugging I think all that's missing is a way for repc to record its requests and responses in such a way that a customer can share them with us. Yes?

If can you suggest a mechanism that is easyish and works in the wasm context?

**Comment by phritz** [comment]
we decided we are not going to do anything for this for now, but will spin off another bug to capture logging more long term
