### ISSUE TITLE
Do something about JSON between repc and repliache-sdk-js

### ISSUE THREAD

**Issue by aboodman** [rocicorp/repc#167]
Looks like right now the majority of the perf profile for scan is JSON encoding:

<img width="982" alt="Screen Shot 2020-09-05 at 3 09 04 PM" src="https://user-images.githubusercontent.com/80388/92316445-dae4a200-ef8f-11ea-864e-44a24d815a11.png">

I'm not sure if we can do better by using a better JSON library. But stepping back and thinking about what's happening here:

1. We read an ArrayBuffer out of IDB
2. We copy the contents of the AB into a Rust Vector (boo, but this is an easy one - see #166)
3. We lay a FlatBuffer down onto the Rust Vector (yay)
4. We iterate the FlatBuffer and create ScanItems. The keys and values inside the items are references. (yay!)
5. For each ScanItem we create a temporary `embed::ScanItem` and allocate its key/value string (boo)
6. We build up a big `Vector<embed::ScanItem>`(boo)
7. We JSON serialize the whole shebang to a String (boo)
8. Then we send the string out to JS
===
9. JS SDK immediately parses the string as JSON (#162)

**Comment by aboodman** [comment]
I have no idea how close we can get to this, but it would be really neat if we could:

1. Read ArrayBuffer out of IDB
2. Lay a Chunk view on top of this w/o copy (can def do this - #166)
... 3,4 as today ...
5. Send JS an array of views into the FB that keep the FB alive on the Rust side.

From looking at the profile we should expect this to be insanely fast, as basically the entire profile is doing things other than reading the thing out of IDB and FlatBufferizing it.

Customer can parse the view into JSON (or whatever) if they want, but that's not on us.

**Comment by aboodman** [comment]
Update: I do not think it is realistically possible to avoid some of these copies for a few reasons:

- We can't get rid of the copy at step 2 in https://github.com/rocicorp/repc/issues/167#issue-694224641 because it is unsafe. Rust can't get a view in the memory backed by the JS VM because it can't trust it won't move (https://rustwasm.github.io/wasm-bindgen/api/js_sys/struct.Uint8Array.html#method.view).
- There's going to be one extra copy if JSON is used because AFAICT `JSON.parse()` has to have a string as input (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse). So we have to decode this data into a JSON string, then immediately parse that. BOO.

However: the big thing in the profile appears to be JSON encoding, and we can get rid of all of that. We don't actually need to send JSON to JS. We're in process! wasm_bindgen supports relatively rich interop, we can send all kinds of things. We can create and integrate with all manner of `JsValues`, including `ArrayBuffer`.

One idea:

Instead of building up a `Vector<embed::ScanItem>` then serializing that to JSON, then sending that to JS and parsing it, why don't we build up a `JSArray` containing key/value pairs where the data is actually a JS `UInt8Array` view onto the original `ArrayBuffer` that came out of IDB. This would require reworking some things, notably `prolly::Entry` will have to have a way to get back to the original ArrayBuffer that its Chunk was built from. If we did this, things would instead look like:

1. Immediately copy from ArrayBuffer to Rust Vector (but hold onto the original AB)
2. Decode w/ fb
3. Build a JSArray containing UInt8Array views into the ArrayBuffer and return to JS
4. JS copies the ArrayBuffer into a string :( - AFAICT required because JSON.parse requires string as input
5. JS parses the string into JSON

4 and 5 only required if users wants JSON of course. Also if there is some way to parse JSON from an ArrayBuffer than 4 can be eliminated.

===

Another related way to do it:

Instead of constructing a JsArray of Uint8Array, return a JsArray of JsValue that wrap Rust structs, where the Rust struct knows how to get a pointer to Rust vector  to the right location in memory. This is not safe, because any allocations in Rust will invalidate the pointer. But JS can call the method and immediately copy to a string (or whatever). Then we would have:

1. Immediately copy from ArrayBuffer to Rust Vector
2. Decode w/ fb
3. Build a JSArray containing Rust structs with methods like key(), value()
4. value() returns pointer into wasm memory
5. JS immediately copies data at the pointer
6. JS parses the string into JSON

The second method is less invasive, but implies that we will always have two copies of the data on the read path. The first method is more invasive but you can get down to one copy if you don't use JSON (or if there is a way to decode JSON from array buffer that I don't know about).

**Comment by phritz** [comment]
For rn just fix scan and if it turns out to be more general yay

**Comment by aboodman** [comment]
This is basically done.

**Comment by aboodman** [comment]
Where by basically I mean:

> For rn just fix scan and if it turns out to be more general yay

This part is done.
