### ISSUE TITLE
Get rid of RPC layer

### ISSUE THREAD

**Issue by arv** [rocicorp/repc#172]
With Wasm we can expose the functions to JS directly. Instead of doing `invoke("dbName", "open", {})` we could do `open("dbName")` etc. It would get rid of some string allocations and json encoding/decoding.

I haven't full thought through how this would work without a dispatch_loop.

**Comment by aboodman** [comment]
I thought about this quite a lot in #167 . Can we just keep it on that bug?

**Comment by arv** [comment]
Sure.
