### ISSUE TITLE
Design and implement "differential client view"

### ISSUE THREAD

**Issue by phritz** [rocicorp/repc#177]
We would like to add to Replicache a way to return deltas from the client view so that we can improve the performance of pull. This seems to involve two key components:

1. Have a way for the client view to receive from Replicache some state that allows it to compute the delta to return (https://github.com/rocicorp/replicache/issues/74)
2. Have a way to return a delta to the client view (https://github.com/rocicorp/replicache/issues/75).

It's possible that those two issues aren't the design we end with but they are the current best thoughts.

**Comment by aboodman** [comment]
🎇
