### ISSUE TITLE
add a short discussion of multiple tab behavior to the docs

### ISSUE THREAD

**Issue by phritz** [rocicorp/repc#180]
replicache is strongly aligned towards reactive uis, would be a shame if someone had something else in mind and didn't realize potential issues with multiple tabs

**Comment by arv** [comment]
It is not clear to me what we want to do here. I assume update the README.md to add something along the lines of:

## Multiple Tabs

Remember that changes to the underlying data can happen underneath you. These changes can come from the server or from a different tab. If your UI is not reactive (driven solely by the data model) you need to take extra steps to ensure the UI is in sync with the data.

**Comment by aboodman** [comment]
Added a tip:
https://github.com/rocicorp/replicache-sdk-js/blob/master/README.md#-tips

**Comment by phritz** [comment]
thanks!

filed https://github.com/rocicorp/repc/issues/196 to keep track of things we might want to include in the comparison to other solutions (which is not a priority rn).
