### ISSUE TITLE
Customer report that concurrent mutations don't work

### ISSUE THREAD

**Issue by aboodman** [rocicorp/repc#181]
@arv saw that concurrent mutations in the unit tests deadlock, unclear if same issue.

**Comment by phritz** [comment]
pointer from our side: https://github.com/rocicorp/replicache-sdk-js/blob/cc617fbf853b46c39268e50cb59229f76a1f13ca/src/replicache.test.ts#L453 is skipped

**Comment by phritz** [comment]
>  https://github.com/rocicorp/replicache-sdk-js/blob/cc617fbf853b46c39268e50cb59229f76a1f13ca/src/replicache.test.ts#L453 

This test is testing behavior we no longer have so this is WAI unless we want to change how locking works. https://rocicorp.slack.com/archives/C014J5KGBHP/p1600450430008800?thread_ts=1600299620.012000&cid=C014J5KGBHP

**Comment by phritz** [comment]
@aboodman when you fix the test can you close this? I don't think there is anything actionable here other than fixing the test.
