### ISSUE TITLE
split push and pull

### ISSUE THREAD

**Issue by phritz** [rocicorp/repc#182]
- issue in old repo: https://github.com/rocicorp/replicache/issues/72 
- from slack:
---
we should tear apart sync.
We assume that all real uses of Replicache will rely on push messaging. So what happens when you add push to the mix is:
client a mutates, then calls sync
repc pushes the change
repc pulls the change
app receives a notification that there was a change via push messaging
app calls sync again
every change turns into three requests! (we skip the second push if there's nothing new) (edited) 
also since pull is slower for many customers, this doesn't double the overhead it way more than doubles it.
Instead what should happen is:
app makes change
repc pushes change (no pull)
server sends notif to all clients (including calling client that there were changes)
repc pulls

**Comment by phritz** [comment]
This is done (thanks arv).

**Comment by aboodman** [comment]
💯
