### ISSUE TITLE
Simplify clientID

### ISSUE THREAD

**Issue by aboodman** [rocicorp/repc#183]
Right now we're generating a fully-fledged uuid. This is more precise than we need. Should we back off to a random 64 bit number, or maybe 128b number?

**Comment by phritz** [comment]
This like birthday paradox. We are randomly throwing m balls (clientids and adversary guesses) into n bins (points in the clientid space) and we want to know for a given m how large does n have to be such that the probability of two balls in the same bin is very small. The rule of thumb is n > m^2. If we give an adversary 1000 guesses a second every day for a year and say that we have a clientid for every person on earth this is m=1000*86000*365 + 7,000,000,000 so n should have at least log_2((1000*86000*365 + 7,000,000,000)^2) =~ 70 bits. So rule of thumb would say at least 70 bits.

**Comment by phritz** [comment]
The chart in https://en.wikipedia.org/wiki/Birthday_attack is really useful. If we use 128 bits and give them 10 years of 1000 guesses/second (roughly 10^11) they still only have a 1/10^15 probability of colliding :) But on the other hand if we use 64 bits then they have a very good chance of guessing one in less than a year at that rate.

**Comment by phritz** [comment]
Gah, did I tell you my brain wasn't working today? Was thinking about laying in bed and realized guesses aren't filling bins so it's not birthday paradox if we want to do the adversarial calculation, it's binomial trials. But the birthday paradox is good for seeing how big the space has to be to not select dups.

Regarding not selecting dup clientids: birthday paradox tells us we have a good chance of collisions when the number of clientids is roughly the square root of the size of the clientid space. So to have space for a clientid for everyone on earth we'd want 7,000,000,000^2 =~ 1*10^20 possible clientids, which is 66 bits worth. So we need at least 66 bits to prevent clientid collisions.

Regarding an adversary guessing a clientid, use the binomial distribution. Suppose we give an adversary 1000 guesses a second for a year (number of trials n=1000*86000*365). We want number of successes to be k=0. The probability of a single success if we've issued 7B clientids is p=7,000,000,000/2**b where b is how many bits in the client id. The numbers are quite big but plugging them eg https://www.statskingdom.com/1_binomial_distribution.html shows that if we use 64 bits the adversary will almost certainly guess one. 

Let's pick 128.

**Comment by aboodman** [comment]
On Thu, Sep 17, 2020 at 8:48 PM Phritz <notifications@github.com> wrote:

> Let's pick 128.
>
Done.

Recall that the client ID is scoped per account - we don't care about
having collisions across accounts. But hey, we'll eventually have some
pretty big individual customers too. Any who cares about a 128b string in
the scheme of things.
