### ISSUE TITLE
let's make clientview info more useful

### ISSUE THREAD

**Issue by phritz** [rocicorp/repc#225]
when developing bindings one wants to know what happened during sync. however during pull we
- return no information about the request from the client to the diffserver and
- only return clientviewinfo if the request from diffserver to data layer was successful. and not, for example, if that connection was refused.

beginsync should return more complete information about the pull, including:
- status code and error if any in request to diffserver. we should return this information even if the connection was refused or we couldnt send the request for some reason.
- clientviewinfo should include an error message if it doesn't send the request or if it fails for some other reason, eg no client view url configured

**Comment by aboodman** [comment]
@phritz is this still actionable or has it been obsoleted by other bugs.

**Comment by phritz** [comment]
right nothing actionable here atm, if there are needs they will emerge
