### ISSUE TITLE
Return result in uuid/mod

### ISSUE THREAD

**Issue by arv** [rocicorp/repc#248]
Instead of crashing

https://github.com/rocicorp/repc/blob/ba43e47b33e5e3d32df82823d512fcc5ec831d1b/src/util/uuid/mod.rs#L15

**Comment by phritz** [comment]
arv this is assigned to you but unless you are going to do it asap i can knock it out. if you unassign yourself i can get to it. (i'm trying to burn through all the small issues from the milestone)

**Comment by arv** [comment]
I just saw that I have a branch for it... https://github.com/arv/repc/tree/uuid-result Don't know why I didn't finish that. Doing it now. Should be trivial

**Comment by arv** [comment]
We are using `make_random_numbers` in a static block. I'm tempted to add a fallback to `Math.random()` but in theory `crypto.getRandomValues` is available [everywhere](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues#Browser_compatibility).

**Comment by phritz** [comment]
that static block doesn't require crypto randomness so math.random() is fine, just add a comment

**Comment by arv** [comment]
In theory `Math.random()` can also fail... anything that touches JS or DOM from Rust's point of view can fail. The question is just at what level we say that we trust the JS/DOM environment to work as expected?
