### ISSUE TITLE
RFC: Overall approach

### ISSUE THREAD

**Issue by aboodman** [rocicorp/repc#3]
# repc — from keys to values and back again.

This bug describes the high-level architectural approach to rewriting replicache-client in Rust. Note that all the examples are in psuedo-Go because all eyes on this still know Go better 😂.

## Layercake

```
+---------------------------------------------------------------------+
| RPC       | Simple, stateless cross-lang interface (port of `repm`) |
+---------------------------------------------------------------------|
| DB        | Top-level Replicache interface (port of Go `DB`)        |
+---------------------------------------------------------------------|
| ProllyMap | Implements map prolly tree atop DAG                     |
+---------------------------------------------------------------------|
| DAG       | Content-addressed DAG store with ref-counting           |
+---------------------------------------------------------------------|
| KV        | Abstracts underlying storage requirements               |
+---------------------------------------------------------------------+
```

## RPC

RPC implements a straight port of the existing `repm` package from Go.

I think it can/should even be bytewise compatible for now. We might want to make this better in the future, but let's cut scope and do it the same way for now.

## DB

This is a straight port of `db.DB` from Go. It doesn't need to have exact same interface, because its only purpose is to support `RPC`. But I don't think we need to think too hard about it -- what we have in Go seems to work well.

Each DB instance (e.g., each Replicache *client*) will own a DAGStore.

(*Note:* There's a tradeoff here -- DAGStore writes are serialized, so if we give each DB one, they can write in parallel, but they won't share chunks. In practice I don't really think either of these considerations matter all that much, and neither way seems easier, so vague pref for performance 🤷‍♂️?)

We can basically port the exact DAG we store in Noms to this, except that we don't have to use wonky Noms `Value` types -- we can encode the dag however we like. I expect it makes sense to use FlatBuffers or something like it. At least in Noms, we found that eliminating copies during decoding were one of our biggest perf wins.

### Implementation Sketch

(error handling omitted for brevity)

```
type Commit struct {
  Name string
  Args json.RawMessage
  Parent Hash
  Value Hash
}

func ExampleIncrementTransaction(key string, delta int) {
    kv := NewIDBStore()
    cs := NewDAGStore(kv)
    tx := cs.Write()

    // Get the existing commit
    headHash, _ := tx.GetHead([]byte("main"))
    headChunk, _, _ = tx.Get(headHash)
    var commit Commit
    // Note: Using JSON in this example for illustrative purposes.
    // Serialization is a choice of DB. Lower layers don't care.
    json.Unmarshal(headChunk, &headCommit)

    // Get the existing prolly map
    mapRoot := headCommit.Value
    m := NewProllyMap(mapRoot, tx)

    // Get the current value if any
    count := 0
    buf, ok, _ := m.Get([]byte(key))
    if ok {
        DecodeInt(buf, &count)
    }

    // Update the current value in the map
    count += delta
    m.Set([]byte(key), EncodeInt(count))

    // Flush the map changes to in-progress WriteTransaction
    mapRoot, _ = m.Flush(tx)
    refs := []Hash{headHash, mapRoot}

    // Create and store new head
    headCommit = Commit{
        Name: "increment",
        args: json.Marshal(map[string]interface{}{"key": key, "delta": delta}),
        Parent: headHash,
        Value: mapRoot,
    }
    cj, _ := json.Marshal(c)
    headChunk = NewChunk(cj)
    tx.Put(headChunk, refs)

    // Update head
    headHash = headChunk.Hash()
    tx.SetHead([]byte("main"), headHash)

    // Commit everything!
    tx.Commit()
}
```

## ProllyMap

ProllyMap implements a large sorted `Map<[]byte, []byte>` using a [Prolly Tree](https://github.com/attic-labs/noms/blob/master/doc/intro.md#prolly-trees-probabilistic-b-trees). 

### Interface Sketch

```
// The subset of ReadTransaction that ProllyMap relies upon.
type ProllySource interface {
    Has(h Hash) (bool, error)
    Get(h Hash) (Chunk, bool, error)
}

// The subset of WriteTransaction that ProllyMap relies upon.
type ProllySink interface {
    Put(h Hash, c Chunk, refs []Hash) error
}

// ProllyMap is analogous to MapEditor from Noms (not Map) in
// that it is an editable view on a map. Change are accumulated
// internally in memory. To write the changes, call Flush() which calculates the
// changes to the prolly tree and writes out the new chunks to the provided sink.
func NewProllyMap(root Hash, s ProllySource) ProllyMap

type ProllyMap struct {
    Has(key []byte) (bool, error)
    Get(key []byte) ([]byte, bool, error)
    Scan(opts ScanOpts) <-chan ScanItem
    Set(key, val []byte) error
    Del(key []byte) error
    Flush(s ProllySink) (newRoot Hash, err error)
}
```

## DAG

This layer implements a transactional content-addressed DAG store atop KV.

DAGStore stores a single directed acyclic graph with zero or more roots. Nodes in the DAG are called *chunks*, and are opaque byte arrays that have a `Hash()` and can refer to other chunks. `DAGStore` tracks the number of references to each chunk internally and drops chunks from storage that are no longer used. There is no delete - delete is implicit when a chunk's refcount drops to zero.

Note that in contrast to Noms, this layer does not define anything about what's inside a chunk. That's entirely up to the layers above.

```
type Hash []byte
type Chunk []byte

type ReadTransaction struct {
    GetHead(key []byte) (Hash, bool, error)
    HasChunk(h Hash) (bool, error)
    GetChunk(h Hash) (Chunk, bool, error)
}

type WriteTransaction struct {
    ReadTransaction

    // It is allowed to write chunks out of order. However by the
    // time Commit() is called, all referred-to chunks must be present.
    SetHead(key []byte, h Hash) error

    // PutChunk buffers a chunk in memory within the transaction. It is visible to
    // ReadTransaction interface, but nowhere else.
    //
    // Caller must ensure that a given Hash always maps to same Chunk and refs.
    // WriteTransaction will not write a chunk of the given hash is already present.
    //
    // PutChunk stores the refs alongside the chunk, which probably also contains
    // them. This might seem wasteful, but internally the chunk is compressed which
    // removes this duplication.
    PutChunk(h Hash, c Chunk, refs []Hash) error

    Abort() error

    // 1. For each added or updated head, increment each referred to chunk's count
    // 2. If chunk not present, retrieve it from WriteTransaction buffer, write it, set refcount to 1, then do step (1) again on it
    // 3. For each deleted or updated head, decrement each referred to chunk's count
    // 4. If a count drops to zero delete that chunk and do step (3) again on it
    // 5. For debug sanity check: warn about any Put() chunks that weren't written by step (2)
    // 6. Commit underlying KV write tx
    //
    // Commit guarantees that change made and effects thereof (e.g., dropped chunks due to
    // refcounts) are immediately visible after Commit returns successfully.
    Commit() error
}

type DAGSource struct {
    Read() ReadTransaction
}

type DAGSink struct {
    Write() WriteTransaction
}

type DAGStore struct {
    DAGSource
    DAGSink
}
```

## KV

KV abstracts away replicache-client's requirements on underlying storage. It is a simple transactional key/value store from `[]byte` to `[]byte`.

We expect to have a few different implementations of this, depending on the platform we are working on.

See #2 for WIP on this interface.

**Comment by phritz** [comment]
this looks great. it is easy to understand and i love how the prollymap is not baked down in a lower layer, the way you have this factored is far more understandable to me. just some minor comments. (btw thanks for the most recent edit, really helpful. anyone else it is worth re reading the issue given aarons most recent update.)

- "rpc" is not really a remote call and we already have an rpc concept in the stack, so suggest we call this something else. database api / dbapi? cache api?
- db: the model is that the chunkstore is owned and only accessed by the db, and there is at most one instance of that db running at a time, correct?
- db: we have talked about this before but i dont think sync requires any special interfaces from db. that is, its not clear to me that it couldn't be built on top of db instead of inside it. like, db could provide everything sync needs but have a tighter more focused interface and implementation by not having sync *in* it. i can imagine db being useful without sync, or wanting different sync protocols, and those things are a little awkward with sync 'inside' the database (seeing http calls inside a database is also a little weird to me). put another way, seems like we could make the db do one thing, store and retrieve data. i can absolutely get with continuing the current program, just if we wanted to do it differently now would be the time.
- is it a goal to enable someone to use replicache without sync, just as a local store? it's an interesting thought exercise, eg compaction of the commit history becomes much more important and we'd probably separate the interfaces that are db-like and sync-like.
- "chunkstore This layer implements a transactional content-addressed chunk store atop KV" -- we could maybe more precisely call this a dag store if we wanted. chunkstore sounds like a way to store blobs but this thing has heads and refs too.
- i really like how the layer above chunkstore keeps track of refs and determines encoding. this is very nicely factored.
- ExampleIncrementTransaction 
   - small mixups in the example: parent should be set to headhash, maproot needs to be added to refs before the head chunk is put, and the sethead should set it to the hash of the new headchunk
    - can you tell me about how commit works with respect to heads, eg what happens if head main was changed by another tx while this one is running?
    - when we are getting the existing commit, tell me about getting the head from cs instead of from the tx? i would have expected the latter.
- i know you have a step by step for commit but could you flesh it out in pseudo code? (no rush, after vaca). i would like to understand the logic of ref counting a little better esp when writing new chunks that are not yet referenced and rolling back a tx.
- first few reads i was a little confused by what actually happens when you flush chunks into and put chunks into the transaction. there is mention that they are stored in a WriteTransaction buffer, meaning they dont go into the chunkstore immediately. however "flush" made me think that the chunks are being written into underlying storage, but i see on re reading that they are flushed to the tx. might be worth saying a few words about the write buffer as a concept. 
- it strikes me that the system doesn't care if prollymap is actually doing anything. for expedience the first prollymap impl could just serialize the map into single chunk, no deduping or anything. that would be quick and easy to implement and would exercise the interfaces, but not require a full prolly tree implementation. that could happen in parallel, or later once the system is working. (and then we could compare the naive way and the prolly way on a real workload.) just a thought.

anyway, this is a really nice design

**Comment by aboodman** [comment]
@phritz I will reply to your comments in detail later, but I just want to say one thing:

> it strikes me that the system doesn't care if prollymap is actually doing anything. for expedience the first prollymap impl could just serialize the map into single chunk, no deduping or anything

Awesome! I hadn't thought about that. ProllyMap is definitely the most gnarly bit here, I think. I started working through the incremental build algorithm again last night and it's quite pretty. But it would be very useful to do something quick and dirtly that allows us to stick the whole stack together. Thanks for pointing this out.

Another opp like this in the design - refcounting. We don't need to implement that to get the whole thing stitched together.

**Comment by aboodman** [comment]
> i know you have a step by step for commit but could you flesh it out in pseudo code? (no rush, after vaca). i would like to understand the logic of ref counting a little better esp when writing new chunks that are not yet referenced and rolling back a tx.

Here you go. There's no explicit work to rollback a tx. It happens automatically by virtue of being built atop the lower-level kvstore's transaction.

```
package dagstore

func key(ns string, name string) string {
    // Note: in real life this will be in terms of []byte, but this is more complex.
    // See: https://www.cockroachlabs.com/blog/sql-in-cockroachdb-mapping-table-data-to-key-value-storage/
    return fmt.Sprintf("%s/%s", ns, name)
}

type WriteTransaction struct {
    // The underlying WriteTransaction from KVStore
    // Note that because kvstore.WriteTransaction buffers pending
    // changes in memory this acts as a writeback cache for our
    // dagstore tx.
    kv *kvstore.WriteTransaction
}

func (tx *WriteTransaction) PutChunk(c Chunk) error {
    if tx.kv.Has(key("chunks", c.Hash())) {
        return nil
    }
    return tx.insChunk(c)
}

func (tx *WriteTransaction) SetHead(key string, h Hash) error {
    return tx.kv.Set(key("heads", key), h)
}

// GetChunk, HasChunk, GetHead are implemented just reading through to tx.kv

func (wx *WriteTransaction) Commit() error {
    // Starting at the changed roots, crawl the dag and adjust refcounts
    for k, nv := range wx.kv.Scan(ScanOpts{Prefix:"heads/"}) {
        ov := tx.kv.GetOriginalValue(k)
        if nv != nil {
            wx.ref(DecodeHash(nv), true)
        }
        if pv != nil {
            wx.ref(DecodeHash(pv), false)
        }
    }

    // Remove any chunks that are now have zero references.
    // This can be chunks that dropped to zero due to head changes,
    // or chunks added by this tx that never got referenced by a head.
    for k, v := range wx.kv.Scan(ScanOpts{Prefix:"counts/"}) {
        count := DecodeInt(v)
        if count == 0 {
            wx.delChunk(DecodeHash(k.StripPrefix("counts/")))
        }
    }
	return wx.kv.Commit()
}

func (wx *WriteTransaction) insChunk(c Chunk) error {
    tx.kv.Set(key("chunks", c.Hash()), c.Data())
    tx.kv.Set(key("counts", c.Hash()), EncodeInt(0))
    tx.kv.Set(key("refs", c.Hash()), EncodeRefs(c.Refs()))
}

func (wx *WriteTransaction) delChunk(h Hash) error {
    wx.kv.Del(key("chunks", h))
    wx.kv.Del(key("counts", h))
    wx.kv.Del(key("refs", h))
}

func (wx *WriteTransaction) ref(h Hash, add bool) error {
    count, ok, err := wx.kv.Get(key("counts", h))
    chk.True(ok) // corrupt db

    if add {
        count++
    } else {
        count--
    }

    chk.True(count >= 0)
    wx.kv.Set(key("counts", h), count)

    // If the chunk is being born or dying, recurse on its children.
    if count == 0 || count == 1 {
        refs, ok, err := wx.kv.Get(keys("refs", h))
        chk.True(ok)
        for _, h := range DecodeRefs(buf) {
            wx.ref(h, add)
        }
    }
}
```

**Comment by aboodman** [comment]
> "rpc" is not really a remote call and we already have an rpc concept in the stack, so suggest we call this something else. database api / dbapi? cache api?

What is the other rpc you have in mind in the stack? I realize this is not the common usage of the term, but I believe it is [technically correct](https://en.wikipedia.org/wiki/Remote_procedure_call), and more descriptive of the package's purpose than "api".

> db: the model is that the chunkstore is owned and only accessed by the db,

Yes.

> and there is at most one instance of that db running at a time, correct?

No. We cannot prevent multiple instances of the same DB from running at once. Think of e.g., tabs in a web browser. The locking that kvstore impls provide must be an device-level lock, not in-memory. (On the web, IndexedDB does this already, built-in).

> db: we have talked about this before but i dont think sync requires any special interfaces from db. that is, its not clear to me that it couldn't be built on top of db instead of inside it. like, db could provide everything sync needs but have a tighter more focused interface and implementation by not having sync in it. i can imagine db being useful without sync, or wanting different sync protocols, and those things are a little awkward with sync 'inside' the database (seeing http calls inside a local database is also a little weird to me). put another way, seems like we could make the db do one thing, store and retrieve versioned data. i can absolutely continue the current program, just if we wanted to do it differently now would be the time.

> Is it a goal to enable someone to use replicache without sync, just as a local store? it's an interesting thought exercise, eg compaction of the commit history becomes much more important and we'd probably separate the interfaces that are db-like and sync-like. if you wanted to make the commits more general and not replicache specific we could replace
> ```
> Name string
> Args json.RawMessage
> ```
> with a Meta field that is a hash, which points to a your-choice-encoded chunk of metadata. I think there is value in considering non-replicache and and non-syc use cases if only to look for cases where we could make generalization gains at very low cost.

It seems like this package would be *so* small. Isn't it just basically the commit struct and its serializaion code? It doesn't really seem worth it to create a different package to me just for that, when users can simply use dagstore and prollymap directly. I admit that the db layer might get more complex in the future (e.g., indexes) and in that case, it might make sense to separate them.

> "chunkstore This layer implements a transactional content-addressed chunk store atop KV" -- we could maybe more precisely call this a dag store if we wanted. chunkstore sounds like a way to store blobs but this thing has heads and refs too.

You are right. I considered this, but basically I just don't like the sound of the word "dagstore". I'll try it on for size though, since as you state, it's more accurate.

> small mixups in the example: parent should be set to headhash, maproot needs to be added to refs before the head chunk is put, and the sethead should set it to the hash of the new headchunk

> when we are getting the existing commit, tell me about getting the head from cs instead of from the tx? i would have expected the latter.

whoops, fixed

> can you tell me about how commit works with respect to heads, eg what happens if head main was changed by another tx while this one is running?

In the current proposal, the underlying kv store must ensure mutual exclusion of write transactions. It's impossible for a head to change while a write tx is running.

> i know you have a step by step for commit but could you flesh it out in pseudo code? (no rush, after vaca). i would like to understand the logic of ref counting a little better esp when writing new chunks that are not yet referenced and rolling back a tx.

See https://github.com/rocicorp/repc/issues/3#issuecomment-648711429

> first few reads i was a little confused by what actually happens when you flush chunks into and put chunks into the transaction. there is mention that they are stored in a WriteTransaction buffer, meaning they dont go into the chunkstore immediately. however "flush" made me think that the chunks are being written into underlying storage, but i see on re reading that they are flushed to the tx. might be worth saying a few words about the write buffer as a concept.

This bit was already there:

> ```
>     // PutChunk buffers a chunk in memory within the transaction. It is visible to
>    // ReadTransaction interface, but nowhere else.
> ```

> it strikes me that the system doesn't care if prollymap is actually doing anything. for expedience the first prollymap impl could just serialize the map into single chunk, no deduping or anything. that would be quick and easy to implement and would exercise the interfaces, but not require a full prolly tree implementation. that could happen in parallel, or later once the system is working. (and then we could compare the naive way and the prolly way on a real workload.) just a thought.

Brilliant!

**Comment by phritz** [comment]
> What is the other rpc you have in mind in the stack?

calls between the cli and account service. and probably in the future between diffserver and account service and we should probably use the same thing between client and diffserver (or switch to a new thing we prefer and use that everywhere). https://github.com/rocicorp/account-service/blob/de89f320bc068477d3b0658136fb28db1f314f51/rpc/wrapper.go#L10 

> No. We cannot prevent multiple instances of the same DB from running at once. Think of e.g., tabs in a web browser. The locking that kvstore impls provide must be an device-level lock, not in-memory. (On the web, IndexedDB does this already, built-in).

ah, gotcha. there's some way to recover from a crash, presumably?

```
 func (wx *WriteTransaction) ref(h Hash, add bool) error {
    count, ok, err := wx.kv.Get(key("counts", h))
    chk.True(ok) // corrupt db
```

sorry to get the ol' hobby horse out again, but unless this compiles away for release builds, why intentionally crash your program when you can cleanly return an error? you literally have an error return value right there :) we have no idea what collateral damage there could be by crashing and if this thing is a library then we're potentially taking the application itself down with us. what if we're inside an experimental little feature in their app and their app can function perfectly well without us? we should not decide for the caller how fatal our errors are, we should let the caller decide. and we should give the process every chance to clean up cleanly eg by returning an error up the stack if we possibly can. i do not think this is a client vs server thing, this kind of stuff happens on clients all the time eg https://www.bugsnag.com/blog/sdks-should-not-crash-apps. panicking should be a last resort for when we absolutely cannot continue.</rant>

**Comment by aboodman** [comment]
On Thu, Jun 25, 2020 at 11:28 AM Phritz <notifications@github.com> wrote:

> sorry to get the ol' hobby horse out again
>

You asked for pseudo-code. I ellided error handling :).

**Comment by phritz** [comment]
fair enough :)

this all sounds really good!

**Comment by aboodman** [comment]
> you literally have an error return value right there :)

Also just FYI it would be a different error. If that key isn't in the kvstore, then it means that the database is corrupt -- some code that should have run earlier to put that key there didn't. It's not the same as the error that get returned.

It would be something like:

```
if err != nil {
  return err
}

if !ok {
  return fmt.Errorf("Oh noes, the db is bad")
}
...
```

I just didn't put this goop everywhere so you could see the core of the rc approach.

**Comment by aboodman** [comment]
This doesn't seem useful to keep open anymore.
