### ISSUE TITLE
Let's ditch JSON Patch

### ISSUE THREAD

**Issue by aboodman** [rocicorp/repc#315]
As a part of #290 we accidentally (or at least non-consciously) made JSON Patch public API. It's a lot more general and powerful than we currently need, and makes using slash-separated keys painful.

Let's do something a lot narrower that only supports the features we actually have:

- clearing the entire keyspace
- deleting an entry by key
- setting a key/value pair

**Comment by arv** [comment]
One benefit of using JSON Patch is that it is a standard and servers can hopefully reuse existing libraries.

One thing that wasn't clear yesterday was that the `path` part actually uses _JSON Pointer_ which is very limited. _JSON Path_ on the other hand is very rich.

**Comment by arv** [comment]
Here is a mini design doc. We should document this somewhere:

## Patch Format

This is inspired by [JSON Patch](https://tools.ietf.org/html/rfc6902). It is simplified a bit by not using [JSON Pointer](https://tools.ietf.org/html/rfc6901) and reducing the operations.

Our patch format is JSON. It consists of an `Array` of individual operations. These operations are applied in order from start to end.

```json
[
  {"op": "add", "key": "a", "value": true},
  {"op": "add", "key": "b", "value": 42},
  {"op": "remove", "key": "b"},
  {"op": "clear"}
]
```

### Operations

We support three operations, `add`, `remove` and `clear`

- `add` - Sets a key-value in the Replicache key-value-store. This operation also requires `key` and `value`.

```json
{
  "op": "add",
  "key": "keyName",
  "value": 42
}
```

`key` must be a string and it is the key in the Replicache key-value-store
`value` is any JSON value

- `remove` - removes a key from the Replicache key-value-store. This operation requires a `key` property.

```json
{
  "op": "remove",
  "key": "keyName"
}
```

`key` must be a string and it is the key to remove the Replicache key-value-store

- `clear` - Clears the entire key-value-store. This operation does not take any other properties.

```json
{
  "op": "clear",
}
```

##

**Comment by aboodman** [comment]
Can we please s/add/put/g to make it clear that this also overwrites any
existing entry with same name?

**Comment by arv** [comment]
OK. I was trying to reuse JSON Patch operators.

**Comment by aboodman** [comment]
In that case, `replace` ?

**Comment by arv** [comment]
Ended up with put and del

**Comment by phritz** [comment]
This design sketch sounds great to me. I especially love for us how put/del/clear map directly to the underlying operations. This is gonna make the patches easier to craft and read.

**Comment by aboodman** [comment]
I like it too. I think this design implies that we need `tx.clear()` :).

**Comment by phritz** [comment]
> I like it too. I think this design implies that we need tx.clear() :).

But we have it! As what I was calling an underlying operation, meaning one on the db tx, even if not on the dispatch tx: https://github.com/rocicorp/repc/blob/d5de8c6dabdb0c0ce1bf46555c22dea45f3f7519/src/db/write.rs#L235

**Comment by arv** [comment]
We do not expose it to js or to the RPC
