### ISSUE TITLE
We should ignore any body in the response from the push endpoint

### ISSUE THREAD

**Issue by aboodman** [rocicorp/repc#349]
We don't actually care what the response to push is, as long as it's `HTTP 200`.

But right now we validate that it is `{}` (this dates from a time when there was data in there we cared about).

Several users (incl me :)) have hit this.

**Comment by aboodman** [comment]
https://discord.com/channels/830183651022471199/830183651022471202/841437245558620160

**Comment by arv** [comment]
We used to return MutationInfos

https://github.com/rocicorp/replicache-client/blob/c3e422ab432afcbce1ab31a33e0021d47a192b42/db/push.go#L31-L34

which contained information about whether the mutations succeeded or not.
