### ISSUE TITLE
Get with the prolly'n

### ISSUE THREAD

**Issue by aboodman** [rocicorp/repc#37]
As of #24 we have the 'prolly' layer of the stack, which unblocks other thing. But #24 doesn't actually implement the real prolly tree data structure -- it uses a single chunk for each map, basically duplicating the entire dataset for each single mutation.

Implementation of the real prolly tree datastructure breaks down into a few discrete steps:

- [ ] Build a prolly tree from source data from scratch
- [ ] Implement get/has/scan over the prolly tree
- [ ] Build a prolly tree incrementally: starting with an existing prolly tree, apply some set of splices to obtain a new prolly tree

The algorithm is described here: https://github.com/attic-labs/noms/blob/master/doc/intro.md and here: https://www.dolthub.com/blog/2020-04-01-how-dolt-stores-table-data

**Comment by aboodman** [comment]
# Chunker: Streaming construction of prolly trees

The naive intuition about building a prolly trees described in the links above requires buffering all chunks in memory, because for each layer it:

1. Passes a rolling hash over the source data, breaking it into probabilistically sized chunks
2. Builds an index of those chunks
3. Use (2) as the input to the next layer

A streaming prolly tree builder is necessary to avoid this. Here's a proposal for how to express this in Rust. This will also be the basis for a later proposal for how to express incremental mutations of a prolly tree.

```
enum NodeType {
  Leaf,
  Internal,
}

pub struct Chunker {
  // Whether we're building a leaf or internal ndoe
  type: LeafType,

  // dag write tx to add chunks to
  write: &dag::Write,

  // items accumulating for next chunk
  wip_chunk: Vec<([]u8, []u8)>,

  // chunks for next level up tree, if any
  parent: Option<Chunker>,

  // Assume we have a library that does rolling hashes
  // will rename https://github.com/rocicorp/repc/blob/master/src/prolly/chunker.rs to this
  rollsum: Rollsum,
}

impl Chunker {
  pub fn new(type: LeafType, write: &dag::Write) -> Chunker {
    Chunker{type, write, wip_chunk: Vec::new(), parent: None, rollsum: Rollsum::new()}
  }

  pub fn add_item(&mut self, key: &[u8], val: &[u8]) {
    wip_chunk.add((key, val));
    for b in key.concat(val) {
      if rollsum.is_boundary(b) {
        // We found a chunk boundary
        self->write_chunk();
        break;
      }
    }
  }

  fn write_chunk(&mut self) {
    // assume we have this helper that serializes pending as a flatbuffer
    // I think the two chunk types will be the same except a bit that says whether it's an internal node or not
    // and if it's an internal node, it will add refs to the chunk for each of its entries
    let chunk = create_chunk(self.type, &self.pending);
    self.write.add_chunk(chunk);

    // If necessary create a parent level
    if (self.parent.is_none()) {
      self.parent = Chunker::new(NodeType::Internal, self.write);
    }

    // Send the parent level an item which is the first key in the new chunk, plus the hash of the chunk
    self.parent.add_item(self.pending.first().0, chunk.hash());

    // Reset internal state to start next chunk
    self.pending.clear();
    self.rollsum.reset();
  }

  // Returns the root hash of the finished tree
  pub fn finish() -> String {
    if (!self.pending.empty()) {
      self.write_chunk();
    }
    match self.type {
      Leaf => self.parent.unwrap().finish(),
      Internal => {
        if self.pending.len() == 1 {
          // We've reached a level that has only one child, that child is the root
          return self.pending.first().0
        }
        // Otherwise, keep going up the stack
        self.parent.unwrap().finish()
      }
    }
  }
}
```

**Comment by aboodman** [comment]
Notes for choosing the rollsum algorithm:

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/perkeep/8hNJ1_tmcmE/OHB0v46CCAAJ

**Comment by aboodman** [comment]
Before embarking on the fully prollytree adventure, we should consider whether some simpler data structure would suit our needs.

I believe those needs are:

1. We want to store an ordered key/value map (data should be stored sorted by key, lexicographically)
1. Our underlying storage is DAGStore (implying whatever we do must be content-addressed)
1.  We want efficient seeks and scans (we should only read from idb data proportional to what we actually need)
1. We want efficient inserts (we should only write data proportional to what user specified)

An implementation of a merkle b-tree for Rust exists: https://github.com/bradyjoestar/merklebtree. Similar libraries exist for many languages. Would that work for us? It is quite a lot smaller in source than a prolly tree impl could be. Also prolly trees have some inherent costs (all the hashing) which would be good to avoid in wasm.

**Comment by arv** [comment]
> we don't need different paths of mutations that end at the same state to have the same hash

- Don't we want that to allow efficient diffs?
  - I guess we are only going to diff over the JSON value?
  - How about sharing the underlying data of a chunk. In case of binary data it seems nice to not have to repeat the data on disk. I know we are not keeping a full history of all the data so the data would only be duplicated a few times so maybe it is not a big deal?

**Comment by aboodman** [comment]
> Don't we want that to allow efficient diffs?

You will still tend to have efficient diffs without history independence, particularly when the values you're diffing share a mutation history as ours do. It's only when they *do not* tend to share a mutation history that you really want history independence.

> How about sharing the underlying data of a chunk. In case of binary data it seems nice to not have to repeat the data on disk. I know we are not keeping a full history of all the data so the data would only be duplicated a few times so maybe it is not a big deal?

Data structures like merkle b-trees will still tend to share common data between versions. It's hard to explain this in text (or I'm too lazy) but I can talk about it on Zoom sometime.

**Comment by phritz** [comment]
Closing this one in favor of https://github.com/rocicorp/rocicorp-internal/issues/17
