### ISSUE TITLE
Implement clientID

### ISSUE THREAD

**Issue by aboodman** [rocicorp/repc#45]
Various bits of the Replicache sync protocol rely on having a per-client unique ID that is generated internally. See https://github.com/rocicorp/replicache-client/blob/master/db/config.go.

**Comment by aboodman** [comment]
I'm thinking we can store this in the kv store directly -- namespaced someplace separate from our dag data.

**Comment by arv** [comment]
The old code uses a base57 encoded UUID V4 string. For this version I think we can just store the bytes instead of converting to a string.

**Comment by arv** [comment]
Or use `"0c317bbb-85f9-4854-b47c-18c0660cf6b1"` formatting

**Comment by phritz** [comment]
Part of this issue is not just to implement client id but find where it is used and ensure it is threaded through and used, eg https://github.com/rocicorp/repc/blob/3678fa5b5fbcce0ed061955ebddafa790565017c/src/embed/sync.rs#L63

**Comment by phritz** [comment]
Note see https://github.com/rocicorp/repc/pull/59 which i think "just" needs to be rebased (on top of months of changes).
