### ISSUE TITLE
Implement transactions RPCs in dispatch

### ISSUE THREAD

**Issue by aboodman** [rocicorp/repc#54]
The RPC interface that replicache bindings expect to be exported from wasm is transactional (beginTransaction, commitTransaction, etc). See the Go RPCs `openTransactionRequest`, `closeTransactionRequest`, and `commitTransactionRequest`: https://github.com/rocicorp/replicache-client/blob/master/repm/types.go#L92

See also how `putRequest`, `getRequest`, etc. all embed information identifying the transaction they are requesting as part of: https://github.com/rocicorp/replicache-client/blob/master/repm/types.go#L52.

However, currently in the Rust port, the interface exposed is non-transactional: https://github.com/rocicorp/repc/blob/master/src/dispatch.rs#L172. Each put/get/has executes in its own unique transaction.

We need to implement the proper transactional semantics at the dispatch layer.

This will likely require reworking dispatch.rs to track the set of open transactions per-connection. See the analogous work in Go: https://github.com/rocicorp/replicache-client/blob/master/repm/api.go#L19, and also a brief comment about this in the Rust: https://github.com/rocicorp/repc/blob/master/src/dispatch.rs#L126.

**Comment by aboodman** [comment]
In my mind there are two major approaches to implementing this issue. This comment will summarize some of the tradeoffs and make a proposal. The key question in my mind is how to handle locking of the datastore. If we generalize the current design naively we end up with a model where:

1. IDB implements its own transactional semantics internally
2. We wrap IDB and MemStore in a RWLock to give it the serialization semantics we want

But basically in this model we are writing code more like C++ or Go. We are relying on a RWLock in both IDB and MemStore to enforce the mutual exclusion we want.

We could alternately do something where we push this higher up into the stack, and lean on Rust. If Rust's mutability rules were applied to the entire datastore, it would have precisely the semantics we want: one writer at a time, multiple readers. There wouldn't be any locks, because it would be enforced at compile-time, and it would be guaranteed to work the same way for memstore and idb, because there would only be one implementation.

The downsides of leaning on Rust:

- It's more speculative, might take longer to implement - but I'm pretty sure it will work
- The compile time locking provided by Rust can't see across processes, so we will still get IDB's native behavior there. But that's not really different from doing it with locks.

After writing this out, I think it's worth investigating the compile-time approach for another day or so. See if I can get something working there.

**Comment by phritz** [comment]
Interesting idea. Sounds like a fun distraction tho: not essential and has the potential to eat time that could instead be used to get us closer to a working product for paying customers. My vote is let's not do this. 

If we *did* want to do this then as you say bc there is no mechanism in rust to queue up requests for mut references we'd need to implement that on our own. Which is as you say that we would basically re-implement an async rwlock... which we are already using... so while we'd probably learn a lot I'm not feelin' it. The biggest value i see in doing this is that we could implement a rwlock that was fair instead of arbitrary. But still doesn't seem that important rn. My guess is we are going to have to rework this locking stuff anyway, maybe defer working on it much until we see what the pain points are.

my two pennies

**Comment by phritz** [comment]
just read the slack thread re dispatch loop. if we think this idea is the best idea for the dispatch loop then i am all for it, as we need a solution to that problem so the value of doing seems significant in that light. i wasn't understanding that it was a solution to tx lifetimes in dispatch.

**Comment by aboodman** [comment]
They are separate issues. It is possible to adopt the idea of having a 'connection' own its transactions and dispatch to them internally without adopting the idea of rust enforcing rwlock.

From slack:

> if we did move the locking up to this level then i'm still not sure we would remove it from the lower level bc the apis would behavior so differently i would be worried about our tests not being useful. if we did do away with lower level locking i would want something to detect whether the invariant we want (at most one write tx which is exclusive of all read txs) holds.

We would not have such a strong need for such a test anymore because the rust compiler would make it impossible to violate that invariant. we'd still probably want something at the level of an integration test that fired a bunch of read messages and made sure they were parallel, then write messages and made sure they were serial.

**Comment by whiten** [comment]
First big step of this complete with https://github.com/rocicorp/repc/commit/7e152cb19d09ff76ea0a1238476c589ed4bcb850.

Remaining are to implement read transactions and a method to signal that the user wants one, as well as support for saving writes for later replay and various rebase support options.
