### ISSUE TITLE
rationalizing canonicalizing the json values we store

### ISSUE THREAD

**Issue by phritz** [rocicorp/repc#93]
we canonicalize json both to and from noms values in the diffserver:
https://github.com/rocicorp/diff-server/blob/37135a25431fcd768c82279c9af35e9637b0fac5/util/noms/json/from_json.go#L92
https://github.com/rocicorp/diff-server/blob/37135a25431fcd768c82279c9af35e9637b0fac5/util/noms/json/from_json.go#L84
https://github.com/rocicorp/diff-server/blob/37135a25431fcd768c82279c9af35e9637b0fac5/util/noms/json/to_json.go#L69

1) checksum 

we canonicalize mainly to support computing a checksum over the map we store. original issue https://github.com/rocicorp/replicache-client/issues/31 and impl here https://github.com/rocicorp/diff-server/blob/37135a25431fcd768c82279c9af35e9637b0fac5/kv/checksum.go. when the client pulls from the diffserver it pulls a patch and the checksum ensures that the client and diffserver each have exactly the same map after the patch. the json gets round tripped at least once to go over the network maybe more, so we need to a way to compute the checksum over the same serialization even if client and server are different languages. canonical json was the solution we chose. in particular we chose a canonical json that has a *unique* canonical representation. not all canonical json encodings guarantee uniqueness.

2) other considerations: args, data layer

we decided that beneficial side effects of using cjson to/from noms was that args was also canonicalized. this gives us the properties that:
- the data layer and the client can have *exactly* the same json values. if we did not canonicalize the json args stored in the commit in the client then in push we would pass uncanonicalized json to the data layer which it would store. the diffserver would pull that json and canonicalize it and then return it down to the client. so the client would end up with json that was not exactly the same as the data layer, which we thought was a little iffy.
- if we dont canonicalize args then the commits will definitely not have any chance of being the same on different platforms. i dont think this was a big concern, just an observation.

this stuff came out in https://rocicorp.slack.com/archives/CMQQ9EDML/p1588827243033500?thread_ts=1588826717.030300&cid=CMQQ9EDML and elsewhere.

3) what replicache stores

we agreed that the contract w/replicache is "you give me a string key and an array of json bytes and i will store at that key a canonicalized version of the value. i always give you back the canonicalized value."

4) is json right?

we should spin it out into a separate discussion

**Comment by phritz** [comment]
so i think if we do NOT canonicalize values in the client map then:
- we cannot compute the checksum over the map as we currently do
- values in the client map can flap: you can write json and then read it out again and the pull cjson values and the next time you read it it will be cjson not the json you got before
- writing the same value encoded in two different ways changes the checksum and any hash over the data
(maybe more, not sure)

if we do NOT canonicalize args in the commit in the client then:
- client and data layer may not have exactly the same 

i think :) warrants more discussion / thought.

**Comment by aboodman** [comment]
> we decided that beneficial side effects of using cjson to/from noms was that args was also canonicalized. this gives us the properties that:

I no longer buy this argument (or need to be re-convinced). The properties listed don't seem that important to me.

**Comment by phritz** [comment]
I don't find the argument to canonicalize args compelling at this point either. 

I do think there is a lot of value in having the checksum and I'm not sure there is a simpler way than having a canonical json format (is there?). If we are trying to avoid implementing the cjson format we chose in rust then the easiest path might be to find a canonical json that exists in rust and go and switch to that.

**Comment by aboodman** [comment]
I'm probably forgetting something important, so fill me in but...

If the client is storing a mapping of keys to values where each are byte arrays and diff-server is always providing the authoritative version, do we need to do any canonicalization on the client? It seems like the interface between client and diff-server could be phrased in terms of byte arrays and the checksum is just computed over that. Right now we only send diffs at the key level so this actually works out fine. If we eventually wanted to send finer-grained diffs we might have to send them as byte-level diffs instead.

On the write side, we don't care if the mutations are canonicalized as they are speculative anyway.

**Comment by phritz** [comment]
> If the client is storing a mapping of keys to values where each are byte arrays and diff-server is always providing the authoritative version, do we need to do any canonicalization on the client? 

We need to canonicalize on the client if the json from the diffserver is round-tripped at any point, either before we insert it into the map or after we do. Eg if on the client we dejson a value we have stored in the map in order to mutate it then when we serjson we have to do so canonically else we could easily get a different representation than the server.

I think you are getting at this talking about bytes. If values were just bytes and we sent byte-based diffs then we don't need canonicalization. Now we are getting into the why-json question which I think might be worth trying to re-rationalize.

**Comment by aboodman** [comment]
We talked about this offline. Resolution for now:

- We will not canonicalize in repc at all (yay!)
- Diff-server will still send a JSON patch but the patch will be guaranteed to be only at the "row" level of granularity (conveniently , this is what it currently does)
- The "payload" of each row change in the patch will be encoded as a JSON string
- The client will treat the patch contents as "binary" -- not try and decode them as JSON or do anything with them other than stick them directly into the DB.

**Comment by aboodman** [comment]
I think this is done - it basically turned into a bug on diff-server: https://github.com/rocicorp/diff-server/issues/54.
