### ISSUE TITLE
Add a way to create and commit snapshot type commits

### ISSUE THREAD

**Issue by aboodman** [rocicorp/repc#95]
Currently db/write is hardcoded to only create local commits. We need to create remote ones too.

I'm thinking maybe the interface should be something like:

```
db::Write::new_local_from_head(head_name, args, ...)
db::Write::new_snapshot_from_head(head_name, ...)
db::Write::commit(head_name..)
```

That is: you can create a new write transaction starting at any named head, and then you can commit that transaction to any other named head. Thus you have forking for free.

**Comment by phritz** [comment]
1. IIUC you those `new_*` functions would return new commits with basis set to the head commit on the given branch? If so that sounds overconstrained. I'd rather have more granular calls that I can piece together in the way that I want, eg

```
new_local_with_basis(basis_commit, ...) 
new_snapshot_with_basis(basis_commit, ...)
// (or maybe take basis_hash as an arg, dunno)
```
then for example when we are syncing and go to create our sync branch we can pass in the base snapshot as basis, which is *not* necessarily the head of master. creating a new local commit on current head can still be one line `new_local_with_basis(db.head(head_name)))` or whatever. 

2. I like commit(head_name). However question: do we want to enforce that the caller has awareness of the current head being replaced, kind of like ffwd does in noms?

3. Can we call a "named head" a "branch"?

**Comment by aboodman** [comment]
> IIUC you those new_* functions would return new commits with basis set to the head commit on the given branch?

They would actually return a `db::Write` -- an opened write transaction. The rest of your question is correct - when the write is committed, it creates a `Commit` with the basis set to the head on the given branch.

> then for example when we are syncing and go to create our sync branch we can pass in the base snapshot as basis, which is not necessarily the head of master. creating a new local commit on current head can still be one line new_local_with_basis(db.head(head_name))) or whatever.

You're right I forgot that we don't always fork from head. Good point.

> I like commit(head_name). However question: do we want to enforce that the caller has awareness of the current head being replaced, kind of like ffwd does in noms?

This was necessary in Noms because writes are optimistically locked. It's never possible to be sure that somebody didn't get in and write before you (absent your own locking scheme, which was not even possible to implement on all the places we wanted to run Noms).

In repc I don't believe this is necessary because our writes are pessimistically locked. It is still possible to accidentally write incorrect code of course -- but it *is* possible to use the API correctly, I think (correct me if I'm wrong here).

If the above statement is true then I don't think we should add this feature until we have a need for it. This is just our own internal API we can change it whenever we want.

**Comment by phritz** [comment]
> > I like commit(head_name). However question: do we want to enforce that the caller has awareness of the current head being replaced, kind of like ffwd does in noms?
> 
> This was necessary in Noms because writes are optimistically locked. It's never possible to be sure that somebody didn't get in and write before you (absent your own locking scheme, which was not even possible to implement on all the places we wanted to run Noms).
>
> In repc I don't believe this is necessary because our writes are pessimistically locked. It is still possible to accidentally write incorrect code of course -- but it is possible to use the API correctly, I think (correct me if I'm wrong here).

The only time I can think of is when we are replaying txs during sync. The write lock only lasts as long as a single tx, not the length of the sync, so between replayed transactions on the sync branch new local commits can land on master. Though maybe prudent, I'm not sure there is a lot of value in requiring that to replace head of master you know what head of master is? Dunno.

> Can we call a "named head" a "branch"?

Yes?

**Comment by aboodman** [comment]
> The only time I can think of is when we are replaying txs during sync. The write lock only lasts as long as a single tx, not the length of the sync, so between replayed transactions on the sync branch new local commits can land on master. Though maybe prudent, I'm not sure there is a lot of value in requiring that to replace head of master you know what head of master is? Dunno.

The way I would imagine that working is that you start the write tx to land the sync on master, read the current head, and verify it hasn't moved. IIRC, we have to do very special stuff in this case anyway, so treating it as an error condition that is caught doesn't feel ideal to me in the first place.

Can you think of a case where it is *not possible* to do the right thing currently?

>> Can we call a "named head" a "branch"?
> Yes?

To me, "head" is the more natural term - it's also the term of art from e.g., git. Branch to me implies something that isn't (necessarily) happening here.

**Comment by phritz** [comment]
I'm happy to not have extra checking on setting the head. As you say, we do it manually anyway.

I'm good with calling the head the head, but if not a 'branch' then what do I call the chain of commits back through the basis hashes from a named head to genesis?

Re "you start the write tx to land the sync on master...": now that I think about it, I'm unsure of commit(head_name). Currently we're always creating a new commit when we switch the head so in that sense it is fine. However doesn't it seem a little weird to require creating a new commit to set a head? The conflation of the two steps of creating a commit and setting a head seems like something we might not want. (Granted, doesn't matter in the short term bc we always create a commit when we swap heads.)
